#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

# install essential things like curl and apt-add-repository
sudo apt-get install git meld gitk ttf-ancient-fonts curl software-properties-common python-software-properties python-flake8 -y

# Install git ppa
sudo add-apt-repository ppa:git-core/ppa -y
sudo apt-get update

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
